export const containerClassName = "container flex flex-col w-full lg:w-4/6 xl:w-7/12 mx-auto h-fit my-12 pb-8 pt-4 transition-all ease-in-out delay-100 duration-1000 border bg-white rounded-md border-gray-light shadow-md opacity-80";
export const containerClassNameSession = "container flex flex-col w-full lg:w-4/6 xl:w-7/12 md:flex-row md:items-center mx-auto my-2 md:my-6 pb-4 transition-all ease-in-out delay-100 duration-1000 bg-white border rounded-md border-gray-light shadow-md opacity-90";
export const containerHiddenClassName = "container flex flex-col w-full lg:w-4/6 xl:w-7/12 h-fit my-12 pb-8 pt-4 opacity-0";
export const titleClassName = "text-5xl md:text-4xl my-8 text-center uppercase md:normal-case";
export const paragraphClassName = "my-2 ml-4 mr-4 lg:ml-12 text-left text-2xl lg:text-base";
export const divClassName = "my-4 mx-12 text-left text-2xl lg:text-base";
export const quoteClassName = "text-3xl md:text-lg mt-5 mb-2 mx-12 text-left italic";
export const quoterClassName = "text-3xl  md:text-lg mb-5 ml-20 text-left italic";
export const paragraphBottomClassName = "my-3 pb-4 mx-12 text-left text-2xl lg:text-base";
export const titleSubClassName = "text-4xl md:text-2xl my-4 ml-4 lg:ml-12 text-left uppercase md:normal-case";
export const buttonClassName = "w-fit h-fit mx-auto my-4 p-6 md:p-3 overflow-hidden text-center font-bold uppercase text-2xl md:text-base bg-orange opacity-70 rounded-md transition ease-in-out delay-100 hover:scale-110 duration-200 select-none"
export const containerClassNameSource = "container flex-auto flex-col my-2 md:my-6 pb-4 w-full md:w-4/6 lg:w-7/12 mx-auto items-center overflow-hidden transition-all ease-in-out delay-100 duration-1000 border rounded-md bg-white border-gray-light shadow-md opacity-90";
export const titleSubClassNameSource = "text-4xl md:text-2xl my-4 lg:ml-12 mx-auto w-2/3 text-center lg:text-left uppercase md:normal-case";
export const paragraphClassNameSource = "basis-3/4 my-2 ml-4 mr-2 lg:ml-12 mx-auto text-left text-2xl lg:text-base";
export const sourceImageClassNameWide = "md:w-48 md:h-24 mr-4 ml-2 my-2 lg:mr-12 lg:ml-8 overflow-hidden border rounded-md float-right"
export const sourceImageClassNameBook = "md:w-24 md:h-42 mr-4 ml-2 my-2 lg:mr-12 lg:ml-8 overflow-hidden border rounded-md float-right"
export const sourceButtonClassName = "w-52 h-12 mx-auto md:ml-12 md:my-4 overflow-hidden text-center text-2xl md:text-base uppercase bg-orange opacity-70 rounded-md transition ease-in-out delay-100 hover:scale-110 duration-200 select-none"
export const headerLinksContainerClassName = "container fixed top-0 flex flex-col md:flex-row  mx-auto z-10 md:px-16 h-fit md:h-16 max-w-full lg:max-w-7xl items-center bg-gray-light opacity-85 rounded-b-md text-black"
export const HeaderHomeLinkContainer = "container flex-1 text-gray-dark  items-center text-center mx-auto px-4 py-6 basis-full md:basis-1/5";
export const headerLinkContainerClassName = "container flex flex-grid grid-cols-2 md:flex-row mx-auto items-center text-center basis-full md:basis-4/5 select-none";
export const headerLinkClassName = "text-xl md:text-lg text-gray-dark px-4 py-6 md:py-2 md:basis-1/4 text-center mx-auto md:mx-6 md:transition ease-in-out delay-100 md:hover:scale-110 hover:underline-offset-1 duration-200 bg-gray md:bg-transparent rounded-lg"
export const headerLinkClassNameClicked = "text-xl md:text-lg text-white px-6 py-6 md:py-2 md:basis-1/4 text-center mx-auto md:mx-6 md:transition ease-in-out delay-100 md:hover:scale-110 hover:underline-offset-1 duration-200 bg-gray md:bg-transparent rounded-lg"