export const containerClassName = "container flex flex-col mx-auto my-8 pb-8 border rounded-lg border-gray-light shadow-lg";
export const titleClassName = "text-4xl my-8 text-center";
export const paragraphClassName = "my-3 mx-12 text-left text-lg";
export const divClassName = "my-1 mx-12 text-left text-lg";
export const quoteClassName = "text-2xl my-5 mx-12 text-center italic";
export const paragraphBottomClassName = "my-3 pb-4 mx-12 text-left text-lg";
export const titleSubClassName = "text-2xl my-4 ml-12 text-left";
export const buttonClassName = "w-52 h-12 mx-auto my-4 overflow-hidden text-center text-lg bg-orange opacity-70 rounded-lg transition ease-in-out delay-100 hover:scale-110 duration-200"
export const sourceButtonClassName = "w-52 h-12 ml-12 my-4 overflow-hidden text-center text-lg bg-orange opacity-70 rounded-lg transition ease-in-out delay-100 hover:scale-110 duration-200"